### ISSUE TITLE
Build script does not handle whitespace in path and can result in lost files in parent directories

### ISSUE THREAD

**Issue by nickchoi-aws** [awslabs/live-streaming-on-aws-with-mediastore#3]
Build script cleans up build directory, however, does not handle when whitespace is in working path and result in parent directories being removed and can result in data loss. This should handle whitespace or based on relative paths.

https://github.com/awslabs/live-streaming-on-aws-with-mediastore/blob/816e3ba6ee7c5931c246faf28e439bad0a84a98d/deployment/build-s3-dist.sh#L39-L42

**Comment by tomnight** [comment]
Thanks for the feedback, I have come across this problem myself but will do some testing and address it in the next release.

**Comment by eggoynes** [comment]
Hey nickchoi-aws thank you for the feedback. 

We just released a new version today. Do you still see this problem? Feel free to reopen.
https://github.com/awslabs/live-streaming-on-aws-with-mediastore/releases/tag/v2.0.0
