### ISSUE TITLE
Cloudfront default CachePolicy causes CORS issues 

### ISSUE THREAD

**Issue by jeremygibbons** [awslabs/live-streaming-on-aws-with-mediastore#8]
In its current form, the Live Streaming on AWS with MediaStore solution deploys a CloudFront distribution with the default managed Cache Policy, "Managed-CachingOptimized". As a result CORS and non-CORS requests for the video playlist have the same cache key, and so if you're unlucky, CORS requests may get a non-CORS cached response, and fail.

I would suggest customizing the Cache Policy to add at least the "Origin" header to the cache key. Alternatively, if the standard solution is not modified, could a note about this be added to the implementation guide ?

Thanks

**Comment by morjoan** [comment]
We'll definitely look into this when we work on our next update. Thanks for the feedback!

**Comment by eggoynes** [comment]
Hi @jeremygibbons

We just released a new version today with the Amazon Cloudfront customized to use a Custom Cache Policy that includes the "Origin" header. Hope this helps.
https://github.com/awslabs/live-streaming-on-aws-with-mediastore/releases/tag/v2.0.0

**Comment by jeremygibbons** [comment]
Much appreciated, thanks !
